export const SHOW_MSG='SHOW_MSG'
export const CHANGE_TO_NOT_USE_REQUEST='CHANGE_TO_NOT_USE_REQUEST'
export const CHANGE_TO_NOT_USE_SUCCESS='CHANGE_TO_NOT_USE_SUCCESS'
export const CHANGE_TO_NOT_USE_FAILURE='CHANGE_TO_NOT_USE_FAILURE'

